export const zmrzliny = [
  {
    id: '0',
    name: 'Vanilka – rum',
    backgroundColor: '#fff200',
    color: '#1B1A1A',
    naCepu: 'ano',
  },
  {
    id: '1',
    name: 'Slaný karamel',
    backgroundColor: '#ee7b22',
    naCepu: 'ne',
  },
  {
    id: '2',
    name: 'Bezinka',
    backgroundColor: '#dfc07d',
    color: '#1B1A1A',
    naCepu: 'ano',
  },
  {
    id: '3',
    name: 'Tmavá čokoláda – uzená sůl',
    backgroundColor: '#3c2415',
    naCepu: 'ano',
  },
  {
    id: '4',
    name: 'Mléčný čokoládový shake',
    backgroundColor: '#754c29',
    naCepu: 'ne',
  },
  {
    id: '5',
    name: 'Banán – arašídovo slaninová směs',
    backgroundColor: '#f7941d',
    naCepu: 'ne',
  },
  {
    id: '6',
    name: 'Bourbon – sušenky z kukuřičných lupínků',
    backgroundColor: '#2b3990',
    naCepu: 'ano',
  },
  {
    id: '7',
    name: 'Káva arabica',
    backgroundColor: '#8b5e3c',
    naCepu: 'ano',
  },
  {
    id: '8',
    name: 'Oolong čaj',
    backgroundColor: '#71732f',
    naCepu: 'ano',
  },
  {
    id: '9',
    name: 'Masala čaj',
    backgroundColor: '#e12b27',
    naCepu: 'ne',
  },
  {
    id: '10',
    name: 'Černé pivo',
    backgroundColor: '#231f20',
    naCepu: 'ne',
  },
  {
    id: '11',
    name: 'Med – grahamové sušenky',
    backgroundColor: '#f79441',
    naCepu: 'ne',
  },
  {
    id: '12',
    name: 'Zázvor v řeckém jogurtu',
    backgroundColor: '#469172',
    naCepu: 'ne',
  },
  {
    id: '13',
    name: 'Bílá čokoláda s mákem',
    backgroundColor: '#c2b59b',
    color: '#1B1A1A',
    naCepu: 'ne',
  },
  {
    id: '14',
    name: 'Pražená bílá čokoláda – levandule',
    backgroundColor: '#7f3f98',
    naCepu: 'ne',
  },
  {
    id: '15',
    name: 'Borůvky v řeckém jogurtu – levandule',
    backgroundColor: '#4c2d85',
    naCepu: 'ne',
  },
  {
    id: '16',
    name: 'meruňka – červený rooibos',
    backgroundColor: '#FF9967',
    color: '#1B1A1A',
    naCepu: 'ne',
  },
  {
    id: '17',
    name: 'Broskev – černý čaj',
    backgroundColor: '#f26522',
    naCepu: 'ne',
  },
  {
    id: '18',
    name: 'Ananas – zelený čaj s jasmínem',
    backgroundColor: '#cbd63f',
    color: '#1B1A1A',
    naCepu: 'ne',
  },
  {
    id: '19',
    name: 'Máta & pepř – kousky čokolády',
    backgroundColor: '#00a79d',
    naCepu: 'ne',
  },
  {
    id: '20',
    name: 'Šípek',
    backgroundColor: '#a32823',
    naCepu: 'ne',
  },
  {
    id: '21',
    name: 'Smetanový sýr – ostružinový vír',
    backgroundColor: '#40016b',
    naCepu: 'ne',
  },
  {
    id: '22',
    name: 'Donut',
    backgroundColor: '#dfc07d',
    color: '#1B1A1A',
    naCepu: 'ne',
  },
  {
    id: '23',
    name: 'Leche merengada – citronová tříšť',
    backgroundColor: '#1b75bc',
    naCepu: 'ne',
  },
  {
    id: '24',
    name: 'Pomerančový sorbet – šafrán',
    backgroundColor: '#f15a29',
    naCepu: 'ano',
  },
  {
    id: '25',
    name: 'Hrušky & rýnský ryzlink sorbet – zázvor',
    backgroundColor: '#8dc63f',
    color: '#1B1A1A',
    naCepu: 'ne',
  },
  {
    id: '26',
    name: 'Merlot & cola sorbet',
    backgroundColor: '#601d25',
    naCepu: 'ne',
  },
  {
    id: '27',
    name: 'Kokos & limetka sorbet – chilli',
    backgroundColor: '#00a14b',
    naCepu: 'ne',
  },
  {
    id: '28',
    name: 'Citron sorbet – bazalka',
    backgroundColor: '#D3FA37',
    color: '#1B1A1A',
    naCepu: 'ne',
  },
  {
    id: '29',
    name: 'Maliny – šampaňské sorbet',
    backgroundColor: '#eb284c',
    naCepu: 'ano',
  },
];

export const gameAnswers = {
  q1: {
    a1: ['22', '6', '11', '0'],
    a2: ['19', '29', '3', '10'],
    a3: ['7', '25', '8', '9'],
    a4: ['28', '24', '5', '14'],
    a5: ['18', '15', '21', '27'],
  },
  q2: {
    a1: ['28', '14', '15', '21'],
    a2: ['18', '5', '3', '27'],
    a3: ['10', '29', '11', '19'],
    a4: ['0', '22', '6', '8'],
    a5: ['7', '24', '25', '9'],
  },
  q3: {
    a1: ['7', '8', '25', '9'],
    a2: ['21', '15', '14', '29'],
    a3: ['19', '3', '6', '11'],
    a4: ['28', '27', '24', '18'],
    a5: ['5', '22', '10', '0'],
  },
  q4: {
    a1: ['18', '28', '5', '27'],
    a2: ['8', '11', '6', '19'],
    a3: ['0', '10', '22', '3'],
    a4: ['7', '24', '9', '25'],
    a5: ['21', '15', '14', '29'],
  },
  q5: {
    a1: ['21', '19', '3', '8'],
    a2: ['29', '14', '6', '11'],
    a3: ['28', '7', '27', '24'],
    a4: ['18', '5', '9', '25'],
    a5: ['0', '22', '10', '15'],
  },
};
