export const gameResultText = {
  headline: ['KASKADÉR', 'ROMANTIK', 'SARKASTIK', 'EZOTERIK', 'PÁRTYGIRL/BOY'],
  message: [
    'Nebojíš se výzev, ani ostřejších chutí, vyber si tu nejbláznivější kombinaci a vrhni se do ní po hlavě. Tak jako to děláš vždycky:-) Podráždi chuťový pohárky třeba touhle:',

    'Nevrháš se do divokých kombinací, radši jedeš tak trochu na jistotu, easy, slowly… Zmrz.linu si nepotřebuješ dát proto, aby ses rozptýlil, ale aby pohladila tvoji jemnou duši. Tak co zkusit tuhle?',

    'Nad frajery s klasickou točenou hnědkou se ušklíbáš, stejně jako nad půlkou světa. Pro ostřejší slovo nejdeš daleko, pro ostřejší zmrz.linu to máš taky jenom kousek:',

    'Vnitřní pohoda a harmonie, utečení do jiných světů… K tomu, aby ses v nich mohl zdržet, ti pomůže ta pravá kombinace chutí provoněná trochou orientu. A zenový stav je tu:',

    'Horký léto plný večírků a pártošek - nesmí chybět zmrzlina, ani dobrý drinky. Než se pustíš do koktejlu, nech si namixovat parádní uvolněnou zmrz.linu, naladí tě na zbytek večera. Čekuj, co se bude dít dál...',
  ],
};

export const zmrzliny = [
  {
    id: '0',
    name: 'Vanilka – rum',
    backgroundColor: '#fff200',
    color: '#1B1A1A',
    naCepu: 'ano',
    resultText: 4,
  },
  {
    id: '1',
    name: 'Slaný karamel',
    backgroundColor: '#ee7b22',
    naCepu: 'ne',
  },
  {
    id: '2',
    name: 'Bezinka',
    backgroundColor: '#dfc07d',
    color: '#1B1A1A',
    naCepu: 'ne',
  },
  {
    id: '3',
    name: 'Tmavá čokoláda – uzená sůl',
    backgroundColor: '#3c2415',
    naCepu: 'ne',
    resultText: 0,
  },
  {
    id: '4',
    name: 'Mléčný čokoládový shake',
    backgroundColor: '#754c29',
    naCepu: 'ne',
  },
  {
    id: '5',
    name: 'Banán – arašídovo slaninová směs',
    backgroundColor: '#f7941d',
    naCepu: 'ne',
    resultText: 2,
  },
  {
    id: '6',
    name: 'Bourbon – sušenky z kukuřičných lupínků',
    backgroundColor: '#2b3990',
    naCepu: 'ne',
    resultText: 4,
  },
  {
    id: '7',
    name: 'Káva arabica',
    backgroundColor: '#8b5e3c',
    naCepu: 'ano',
    resultText: 2,
  },
  {
    id: '8',
    name: 'Oolong čaj',
    backgroundColor: '#71732f',
    naCepu: 'ne',
    resultText: 3,
  },
  {
    id: '9',
    name: 'Masala čaj',
    backgroundColor: '#e12b27',
    naCepu: 'ne',
    headline: 3,
    resultText: 3,
  },
  {
    id: '10',
    name: 'Černé pivo',
    backgroundColor: '#231f20',
    naCepu: 'ne',
    resultText: 0,
  },
  {
    id: '11',
    name: 'Med – grahamové sušenky',
    backgroundColor: '#f79441',
    naCepu: 'ne',
    resultText: 4,
  },
  {
    id: '12',
    name: 'Zázvor v řeckém jogurtu',
    backgroundColor: '#469172',
    naCepu: 'ne',
  },
  {
    id: '13',
    name: 'Bílá čokoláda s mákem',
    backgroundColor: '#c2b59b',
    color: '#1B1A1A',
    naCepu: 'ne',
  },
  {
    id: '14',
    name: 'Pražená bílá čokoláda – levandule',
    backgroundColor: '#7f3f98',
    naCepu: 'ne',
    resultText: 1,
  },
  {
    id: '15',
    name: 'Borůvky v řeckém jogurtu – levandule',
    backgroundColor: '#4c2d85',
    naCepu: 'ano',
    resultText: 1,
  },
  {
    id: '16',
    name: 'meruňka – červený rooibos',
    backgroundColor: '#FF9967',
    color: '#1B1A1A',
    naCepu: 'ne',
  },
  {
    id: '17',
    name: 'Broskev – černý čaj',
    backgroundColor: '#f26522',
    naCepu: 'ne',
  },
  {
    id: '18',
    name: 'Ananas – zelený čaj s jasmínem',
    backgroundColor: '#cbd63f',
    color: '#1B1A1A',
    naCepu: 'ne',
    resultText: 3,
  },
  {
    id: '19',
    name: 'Máta & pepř – kousky čokolády',
    backgroundColor: '#00a79d',
    naCepu: 'ne',
    resultText: 2,
  },
  {
    id: '20',
    name: 'Šípek',
    backgroundColor: '#a32823',
    naCepu: 'ne',
  },
  {
    id: '21',
    name: 'Smetanový sýr – ostružinová spirála',
    backgroundColor: '#40016b',
    naCepu: 'ne',
    resultText: 1,
  },
  {
    id: '22',
    name: 'Donut',
    backgroundColor: '#dfc07d',
    color: '#1B1A1A',
    naCepu: 'ne',
    resultText: 1,
  },
  {
    id: '23',
    name: 'Leche merengada – citronová tříšť',
    backgroundColor: '#1b75bc',
    naCepu: 'ne',
  },
  {
    id: '24',
    name: 'Pomerančový sorbet – šafrán',
    backgroundColor: '#f15a29',
    naCepu: 'ne',
    resultText: 3,
  },
  {
    id: '25',
    name: 'Hrušky & rýnský ryzlink sorbet – zázvor',
    backgroundColor: '#8dc63f',
    color: '#1B1A1A',
    naCepu: 'ne',
    resultText: 2,
  },
  {
    id: '26',
    name: 'Merlot & cola sorbet',
    backgroundColor: '#601d25',
    naCepu: 'ano',
  },
  {
    id: '27',
    name: 'Kokos & limetka sorbet – chilli',
    backgroundColor: '#00a14b',
    naCepu: 'ne',
    resultText: 0,
  },
  {
    id: '28',
    name: 'Citron sorbet – bazalka',
    backgroundColor: '#D3FA37',
    color: '#1B1A1A',
    naCepu: 'ano',
    resultText: 0,
  },
  {
    id: '29',
    name: 'Maliny – šampaňské sorbet',
    backgroundColor: '#eb284c',
    naCepu: 'ano',
    resultText: 4,
  },
];

export const gameAnswers = {
  q1: {
    a1: ['22', '6', '11', '0'],
    a2: ['19', '29', '3', '10'],
    a3: ['7', '25', '8', '9'],
    a4: ['28', '24', '5', '14'],
    a5: ['18', '15', '21', '27'],
  },
  q2: {
    a1: ['14', '15', '21', '22'],
    a2: ['8', '9', '18', '24'],
    a3: ['5', '7', '19', '25'],
    a4: ['0', '6', '11', '29'],
    a5: ['3', '10', '27', '28'],
  },
  q3: {
    a1: ['8', '9', '18', '24'],
    a2: ['14', '15', '21', '22'],
    a3: ['5', '7', '19', '25'],
    a4: ['3', '10', '27', '28'],
    a5: ['0', '6', '11', '29'],
  },
  q4: {
    a1: ['3', '10', '27', '28'],
    a2: ['5', '7', '19', '25'],
    a3: ['0', '6', '11', '29'],
    a4: ['8', '9', '18', '24'],
    a5: ['14', '15', '21', '22'],
  },
  q5: {
    a1: ['21', '19', '3', '8'],
    a2: ['29', '14', '6', '11'],
    a3: ['28', '7', '27', '24'],
    a4: ['18', '5', '9', '25'],
    a5: ['0', '22', '10', '15'],
  },
};
